### PR TITLE
Compatible with Symfony ~4.0

### PR DESCRIPTION
**Pull request by Prometee**
This plugin is compatible with Sf 4.0 without any change.

### CODE REVIEW

**Comment by ekyna** [comment]
Thx @Prometee. Will merge in a few days.

**Comment by Prometee** [comment]
Thanks for the merge, I'm making a plugin for Sylius dependent to your repository, you could check it here : https://github.com/Prometee/SyliusPayumMoneticoPlugin

**Comment by ekyna** [comment]
Thx to you @Prometee

In your composer.json you could use :
```"ekyna/payum-monetico": "^1.5"```

And you should read this [PR's thread](https://github.com/ekyna/PayumMoneticoBundle/pull/1) about notify action.

**Comment by Prometee** [comment]
Thanks for the advises ;)
I was using `dev-master` because I need to use my fork until you merge it.

I just made a little bridge for Sylius and it use payum natively, I will test my implementation during September maybe (I've to work on other Sylius Plugin for now). Actually a `Form` manage the settings to put it into the configuration of the current `channel` (multi eshop/site mechanism) and a service definition (with tags) manage the bridge between Sylius <-> Payum <-> Monetico.

**Pull request merged**
